### ISSUE TITLE
Guardar resultados

### ISSUE THREAD

**Issue by martcaro** [martcaro/Graph-based-explanation#3]
Parte servidor para guardar resultados (PHP)

**Comment by jljorro** [comment]
Falta instalarlo en el servidor de GAIA

**Comment by martcaro** [comment]
Hay que incluir también la parte del servidor del mini cuestionario que se le hace al usuario al terminar cada ejemplo

**Comment by jljorro** [comment]
El servidor está arrancado en https://mistela.fdi.ucm.es/jorro/explicaciones.php
